In [1]:
from src.filter_data import filter_data_func
from src.train_model import multiple_poisson, multiple_XGBoost
from src.test_models import test_models

In [2]:
df = filter_data_func(min_date="1920-06-10", max_date="2026-06-10")

In [3]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,home_avg_points_last_10,home_avg_goals_last_10,home_avg_conceded_last_10,away_avg_points_last_10,away_avg_goals_last_10,away_avg_conceded_last_10
0,1920-06-13,Norway,Denmark,1.0,1.0,Friendly,Kristiania,Norway,False,1920,NaN,NaN,NaN,NaN,NaN,NaN
1,1920-06-27,Norway,Sweden,0.0,3.0,Friendly,Kristiania,Norway,False,1920,1.0,1.0,1.0,NaN,NaN,NaN
2,1920-06-27,Switzerland,Germany,4.0,1.0,Friendly,Zürich,Switzerland,False,1920,NaN,NaN,NaN,NaN,NaN,NaN
3,1920-07-18,Uruguay,Argentina,2.0,0.0,Copa Premio Honor Uruguayo,Montevideo,Uruguay,False,1920,NaN,NaN,NaN,NaN,NaN,NaN
4,1920-07-25,Argentina,Uruguay,1.0,3.0,Copa Newton,Buenos Aires,Argentina,False,1920,0.0,2.0,0.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48784,2026-06-09,Armenia,Moldova,1.0,1.0,Friendly,Yerevan,Armenia,False,2026,0.5,2.3,1.5,0.2,2.2,1.9
48785,2026-06-09,Argentina,Iceland,3.0,0.0,Friendly,Auburn,United States,True,2026,2.5,1.5,1.1,0.9,2.2,1.3
48786,2026-06-09,Angola,Central African Republic,3.0,0.0,Friendly,Casablanca,Morocco,True,2026,1.1,1.2,1.1,0.8,0.9,1.7
48787,2026-06-09,Ethiopia,Malawi,1.0,1.0,Friendly,Dire Dawa,Ethiopia,False,2026,1.2,1.6,1.1,1.1,1.1,0.6
48788,2026-06-09,Iraq,Venezuela,0.0,2.0,Friendly,Bridgeview,United States,True,2026,1.8,1.1,0.8,1.0,1.8,1.0

In [4]:
test_scores = test_models(df)

In [5]:
test_scores

   glm_home_score  xgb_home_score  glm_away_score  xgb_away_score
0        1.258666        1.404152        1.336707        1.345869

In [5]:
models_xgboost = multiple_XGBoost(df)

In [4]:
models = multiple_poisson(df)

In [5]:
print(models[0].summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:             home_score   No. Observations:                49401
Model:                            GLM   Df Residuals:                    48557
Model Family:                 Poisson   Df Model:                          843
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -78489.
Date:                Wed, 17 Jun 2026   Deviance:                       60198.
Time:                        19:09:57   Pearson chi2:                 5.52e+04
No. Iterations:                    23   Pseudo R-squ. (CS):             0.3834
Covariance Type:            nonrobust
=======================================================================================================================================
                                                                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------------
const                                                                  13.5090      0.557     24.269      0.000      12.418      14.600
neutral                                                                -0.1232      0.010    -11.747      0.000      -0.144      -0.103
year                                                                   -0.0065      0.000    -36.353      0.000      -0.007      -0.006
home_team_Afghanistan                                                  -0.7664      0.274     -2.795      0.005      -1.304      -0.229
home_team_Albania                                                       0.1537      0.246      0.624      0.533      -0.329       0.637
home_team_Alderney                                                     -1.5800      0.339     -4.660      0.000      -2.244      -0.915
home_team_Algeria                                                       0.4411      0.241      1.829      0.067      -0.032       0.914
home_team_American Samoa                                               -2.2602      0.340     -6.654      0.000      -2.926      -1.594
home_team_Andalusia                                                     0.6693      0.322      2.081      0.037       0.039       1.300
home_team_Andorra                                                      -1.0210      0.281     -3.628      0.000      -1.573      -0.469
home_team_Angola                                                        0.0455      0.245      0.186      0.853      -0.435       0.526
home_team_Anguilla                                                     -2.0063      0.341     -5.876      0.000      -2.675      -1.337
home_team_Antigua and Barbuda                                          -0.5939      0.250     -2.375      0.018      -1.084      -0.104
home_team_Arameans Suryoye                                              0.4950      0.480      1.032      0.302      -0.445       1.435
home_team_Argentina                                                     1.0006      0.240      4.173      0.000       0.531       1.471
home_team_Armenia                                                       0.1299      0.251      0.517      0.605      -0.363       0.623
home_team_Artsakh                                                      -0.0420      0.371     -0.113      0.910      -0.769       0.685
home_team_Aruba                                                        -0.5837      0.256     -2.278      0.023      -1.086      -0.082
home_team_Australia                                                     0.4038      0.241      1.675      0.094      -0.069       0.876
home_team_Austria                                                       0.8044      0.240      3.351      0.001       0.334       1.275
home_team_Aymara                                                       -2.8219   5.11e+04  -5.52e-05      1.000      -1e+05       1e+05
home_team_Azerbaijan                                                   -0.1284      0.252     -0.509      0.611      -0.623       0.366
home_team_Bahamas                                                      -1.2332      0.282     -4.369      0.000      -1.786      -0.680
home_team_Bahrain                                                       0.0132      0.242      0.055      0.956      -0.461       0.488
home_team_Bangladesh                                                   -0.9615      0.250     -3.841      0.000      -1.452      -0.471
home_team_Barawa                                                       -0.5146      0.358     -1.437      0.151      -1.217       0.187
home_team_Barbados                                                     -0.5878      0.247     -2.377      0.017      -1.072      -0.103
home_team_Basque Country                                                1.0410      0.265      3.929      0.000       0.522       1.560
home_team_Belarus                                                       0.2615      0.249      1.051      0.293      -0.226       0.749
home_team_Belgium                                                       0.8391      0.240      3.497      0.000       0.369       1.309
home_team_Belize                                                       -0.6221      0.266     -2.336      0.019      -1.144      -0.100
home_team_Benin                                                         0.0014      0.248      0.006      0.996      -0.484       0.487
home_team_Bermuda                                                      -0.3064      0.248     -1.236      0.216      -0.792       0.179
home_team_Bhutan                                                       -1.2210      0.299     -4.083      0.000      -1.807      -0.635
home_team_Biafra                                                       -1.1316      0.760     -1.489      0.136      -2.621       0.358
home_team_Bolivia                                                       0.5305      0.244      2.176      0.030       0.053       1.008
home_team_Bonaire                                                      -1.1444      0.320     -3.580      0.000      -1.771      -0.518
home_team_Bosnia and Herzegovina                                        0.4537      0.248      1.831      0.067      -0.032       0.939
home_team_Botswana                                                     -0.4609      0.251     -1.837      0.066      -0.953       0.031
home_team_Brazil                                                        1.1220      0.239      4.686      0.000       0.653       1.591
home_team_British Virgin Islands                                       -1.3299      0.271     -4.906      0.000      -1.861      -0.799
home_team_Brittany                                                     -0.2059      0.372     -0.553      0.580      -0.936       0.524
home_team_Brunei                                                       -1.1079      0.278     -3.988      0.000      -1.652      -0.563
home_team_Bulgaria                                                      0.6080      0.242      2.517      0.012       0.135       1.081
home_team_Burkina Faso                                                  0.2064      0.244      0.845      0.398      -0.272       0.685
home_team_Burundi                                                      -0.2851      0.255     -1.116      0.264      -0.786       0.216
home_team_Cambodia                                                     -0.6347      0.248     -2.561      0.010      -1.120      -0.149
home_team_Cameroon                                                      0.2653      0.242      1.094      0.274      -0.210       0.740
home_team_Canada                                                        0.2452      0.245      1.003      0.316      -0.234       0.724
home_team_Canary Islands                                                0.8762      0.385      2.276      0.023       0.122       1.631
home_team_Cape Verde                                                    0.0352      0.252      0.140      0.889      -0.458       0.528
home_team_Cascadia                                                      0.3851      0.414      0.929      0.353      -0.427       1.197
home_team_Catalonia                                                     0.6248      0.267      2.341      0.019       0.102       1.148
home_team_Cayman Islands                                               -1.0496      0.264     -3.975      0.000      -1.567      -0.532
home_team_Central African Republic                                     -0.1153      0.262     -0.439      0.660      -0.630       0.399
home_team_Central Spain                                                 0.0481      1.263      0.038      0.970      -2.428       2.524
home_team_Chad                                                         -0.2001      0.267     -0.750      0.453      -0.723       0.323
home_team_Chagos Islands                                               -0.7081      0.372     -1.906      0.057      -1.436       0.020
home_team_Chameria                                                     -0.0160      0.506     -0.032      0.975      -1.008       0.976
home_team_Chechnya                                                     -0.5224      0.799     -0.654      0.513      -2.089       1.044
home_team_Chile                                                         0.7779      0.241      3.230      0.001       0.306       1.250
home_team_China                                                         0.2601      0.240      1.082      0.279      -0.211       0.731
home_team_Colombia                                                      0.5256      0.243      2.166      0.030       0.050       1.001
home_team_Comoros                                                      -0.4509      0.268     -1.681      0.093      -0.977       0.075
home_team_Congo                                                         0.0886      0.245      0.362      0.718      -0.392       0.569
home_team_Cook Islands                                                 -1.8098      0.322     -5.615      0.000      -2.442      -1.178
home_team_Corsica                                                      -0.2428      0.466     -0.521      0.603      -1.156       0.671
home_team_Costa Rica                                                    0.4527      0.241      1.877      0.060      -0.020       0.925
home_team_County of Nice                                                0.0885      0.442      0.201      0.841      -0.777       0.954
home_team_Croatia                                                       0.8363      0.243      3.442      0.001       0.360       1.313
home_team_Cuba                                                         -0.1648      0.246     -0.671      0.502      -0.646       0.317
home_team_Curaçao                                                      -0.2138      0.245     -0.872      0.383      -0.694       0.267
home_team_Cyprus                                                        0.1146      0.246      0.465      0.642      -0.368       0.597
home_team_Czech Republic                                                0.8361      0.243      3.439      0.001       0.360       1.313
home_team_Czechoslovakia                                                0.9663      0.241      4.002      0.000       0.493       1.440
home_team_DR Congo                                                      0.2602      0.244      1.069      0.285      -0.217       0.738
home_team_Darfur                                                      -23.4382   3.11e+04     -0.001      0.999   -6.09e+04    6.09e+04
home_team_Denmark                                                       0.8314      0.240      3.464      0.001       0.361       1.302
home_team_Djibouti                                                     -0.8363      0.289     -2.895      0.004      -1.402      -0.270
home_team_Dominica                                                     -0.9114      0.254     -3.587      0.000      -1.409      -0.413
home_team_Dominican Republic                                           -0.4198      0.251     -1.672      0.095      -0.912       0.072
home_team_Donetsk PR                                                    0.4799      0.756      0.635      0.526      -1.002       1.962
home_team_Délvidék                                                     -1.1646      1.502     -0.775      0.438      -4.109       1.780
home_team_Ecuador                                                       0.6152      0.243      2.533      0.011       0.139       1.091
home_team_Egypt                                                         0.5064      0.240      2.108      0.035       0.036       0.977
home_team_El Salvador                                                   0.0670      0.242      0.276      0.782      -0.408       0.542
home_team_Elba Island                                                  -0.5792      0.431     -1.345      0.179      -1.423       0.265
home_team_Ellan Vannin                                                  0.2855      0.276      1.036      0.300      -0.255       0.826
home_team_England                                                       0.9518      0.240      3.971      0.000       0.482       1.421
home_team_Equatorial Guinea                                            -0.2811      0.259     -1.085      0.278      -0.789       0.227
home_team_Eritrea                                                      -0.8979      0.346     -2.597      0.009      -1.576      -0.220
home_team_Estonia                                                      -0.0643      0.245     -0.263      0.793      -0.545       0.416
home_team_Eswatini                                                     -0.5299      0.255     -2.076      0.038      -1.030      -0.030
home_team_Ethiopia                                                     -0.0479      0.244     -0.196      0.844      -0.526       0.430
home_team_Falkland Islands                                             -1.2674      0.355     -3.565      0.000      -1.964      -0.571
home_team_Faroe Islands                                                -0.1116      0.249     -0.447      0.655      -0.600       0.377
home_team_Felvidék                                                     -0.7883      0.773     -1.020      0.308      -2.303       0.726
home_team_Fiji                                                         -0.4896      0.246     -1.987      0.047      -0.973      -0.007
home_team_Finland                                                       0.4002      0.242      1.654      0.098      -0.074       0.874
home_team_France                                                        0.8828      0.240      3.685      0.000       0.413       1.352
home_team_Franconia                                                    -0.9812      0.572     -1.714      0.087      -2.103       0.141
home_team_French Guiana                                                -0.3870      0.254     -1.522      0.128      -0.885       0.111
home_team_Frøya                                                        -0.9953      0.307     -3.246      0.001      -1.596      -0.394
home_team_Gabon                                                         0.0038      0.246      0.015      0.988      -0.478       0.485
home_team_Galicia                                                       0.5043      0.395      1.276      0.202      -0.270       1.279
home_team_Gambia                                                       -0.0987      0.250     -0.394      0.693      -0.589       0.392
home_team_Georgia                                                       0.3878      0.247      1.570      0.116      -0.096       0.872
home_team_German DR                                                     0.7490      0.246      3.046      0.002       0.267       1.231
home_team_Germany                                                       1.0747      0.239      4.492      0.000       0.606       1.544
home_team_Ghana                                                         0.3879      0.242      1.605      0.109      -0.086       0.862
home_team_Gibraltar                                                    -0.5757      0.252     -2.284      0.022      -1.070      -0.082
home_team_Gotland                                                      -0.2587      0.280     -0.925      0.355      -0.807       0.290
home_team_Gozo                                                         -0.1320      0.313     -0.422      0.673      -0.745       0.481
home_team_Greece                                                        0.4420      0.242      1.826      0.068      -0.032       0.916
home_team_Greenland                                                    -0.5617      0.270     -2.079      0.038      -1.091      -0.032
home_team_Grenada                                                      -0.3144      0.248     -1.270      0.204      -0.800       0.171
home_team_Guadeloupe                                                   -0.3140      0.247     -1.272      0.203      -0.798       0.170
home_team_Guam                                                         -1.6465      0.274     -6.013      0.000      -2.183      -1.110
home_team_Guatemala                                                     0.1489      0.243      0.614      0.539      -0.327       0.624
home_team_Guernsey                                                     -0.3270      0.263     -1.242      0.214      -0.843       0.189
home_team_Guinea                                                        0.2740      0.244      1.125      0.260      -0.203       0.751
home_team_Guinea-Bissau                                                -0.0933      0.257     -0.364      0.716      -0.596       0.410
home_team_Guyana                                                       -0.4218      0.247     -1.707      0.088      -0.906       0.062
home_team_Găgăuzia                                                     -1.5219      0.780     -1.950      0.051      -3.051       0.007
home_team_Haiti                                                        -0.0392      0.243     -0.162      0.872      -0.515       0.437
home_team_Hitra                                                        -0.8832      0.350     -2.526      0.012      -1.569      -0.198
home_team_Hmong                                                        -0.4198      0.703     -0.597      0.550      -1.798       0.958
home_team_Honduras                                                      0.2437      0.242      1.006      0.315      -0.231       0.719
home_team_Hong Kong                                                    -0.3760      0.243     -1.546      0.122      -0.852       0.101
home_team_Hungary                                                       0.8933      0.240      3.728      0.000       0.424       1.363
home_team_Iceland                                                       0.3165      0.244      1.298      0.194      -0.162       0.794
home_team_India                                                        -0.4498      0.244     -1.847      0.065      -0.927       0.028
home_team_Indonesia                                                    -0.0838      0.241     -0.348      0.728      -0.556       0.388
home_team_Iran                                                          0.3594      0.241      1.493      0.135      -0.112       0.831
home_team_Iraq                                                          0.2901      0.241      1.202      0.229      -0.183       0.763
home_team_Iraqi Kurdistan                                               0.1343      0.307      0.437      0.662      -0.468       0.736
home_team_Isle of Man                                                  -0.1316      0.273     -0.482      0.630      -0.666       0.403
home_team_Isle of Wight                                                -0.4363      0.281     -1.552      0.121      -0.987       0.115